### ISSUE TITLE
sample.py error

### ISSUE THREAD

**Issue by lymanyoung** [inikdom/neural-chatbot#18]
Traceback (most recent call last):
  File "sample.py", line 101, in <module>
    main()
  File "sample.py", line 32, in main
    model = load_model(sess, FLAGS.checkpoint_dir)
  File "sample.py", line 79, in load_model
    hidden_size=FLAGS.hidden_size,
  File "/Users/LymanYoung/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 50, in __getattr__
    raise AttributeError(name)
AttributeError: hidden_size

**Comment by domerin0** [comment]
Hello, I'm aware of problem in the sampling script. I updated the rest of the project for tensorflow 1.1. In doing so I hadn't updated the sampling script yet. Expect an update to it sometime this week. I think your other issue is related to this as well.

**Comment by DhruvMevada** [comment]
Traceback (most recent call last):
  File "C:\Users\dhruv.mevada\Downloads\neural-chatbot-master\neural-chatbot-master\sample.py", line 101, in <module>
    main()
  File "C:\Users\dhruv.mevada\Downloads\neural-chatbot-master\neural-chatbot-master\sample.py", line 32, in main
    model = load_model(sess, FLAGS.checkpoint_dir)
  File "C:\Users\dhruv.mevada\Downloads\neural-chatbot-master\neural-chatbot-master\sample.py", line 72, in load_model
    params = hyper_params.restore_hyper_params(path)
  File "C:\Users\dhruv.mevada\Downloads\neural-chatbot-master\neural-chatbot-master\util\hyperparamutils.py", line 13, in restore_hyper_params
    with open(file_path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'data/checkpoints/1461979205hiddensize_100_dropout_0.5_numlayers_1\\hyperparams.p'
>>>

**Comment by 643245611** [comment]
Hello, have you solved the problem? I have the same problem. Please give me some advice.
