### ISSUE TITLE
No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by judemont** [inikdom/neural-chatbot#29]
Hello, 
When I run `train.py` (`python train.py`) I have this error : 
```
Traceback (most recent call last):
  File "/home/judemont/autre/neural-chatbot/train.py", line 17, in <module>
    import models.chatbot as chatbot
  File "/home/judemont/autre/neural-chatbot/models/chatbot.py", line 15, in <module>
    from tensorflow.contrib import rnn, seq2seq
ModuleNotFoundError: No module named 'tensorflow.contrib'
```
Python Version : `3.11.2`
`tensorflow==2.12.0`
OS : `ubuntu 23.04`

**Comment by vovod** [comment]
tensorflow.contrib is removed from version 2.0, you need install version <= 1.14 to use it.

**Comment by judemont** [comment]
Okay, thanks.
